version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    networks:
    - django-net  
    environment:
       MYSQL_DATABASE: 'djangoapp'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'djangoapppasswd'
       MYSQL_ROOT_PASSWORD: 'djangoapppasswd'
  djangoapp:
    build: .
    command: gunicorn --bind=0.0.0.0:8000 carnival.wsgi
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    networks:
    - django-net
    depends_on:
      - db

networks:
  django-net:
